Console.WriteLine("=============");
Console.WriteLine("BASIC EXAMPLE");
Console.WriteLine("=============");
Lysia.Program.RunFile(["Examples/basic"]);
Console.WriteLine();
Console.WriteLine("=============");
Console.WriteLine("CONDITION EXAMPLE");
Console.WriteLine("=============");
Lysia.Program.RunFile(["Examples/condition"]);
Console.WriteLine();
Console.WriteLine("=============");
Console.WriteLine("LOOP EXAMPLE");
Console.WriteLine("=============");
Lysia.Program.RunFile(["Examples/loop"]);
Console.WriteLine();
Console.WriteLine("=============");
Console.WriteLine("FUNC EXAMPLE");
Console.WriteLine("=============");
Lysia.Program.RunFile(["Examples/func"]);
Console.WriteLine();
Console.WriteLine("=============");
Console.WriteLine("FILE EXAMPLE");
Console.WriteLine("=============");
Lysia.Program.RunFile(["Examples/file"]);
Console.WriteLine();
Console.WriteLine("=============");
Console.WriteLine("IMPORT EXAMPLE");
Console.WriteLine("=============");
Lysia.Program.RunFile(["Examples/import"]);