Console.WriteLine("=============");
Console.WriteLine("BASIC EXAMPLE");
Console.WriteLine("=============");
Lysia.Program.RunFile(["Examples/basic"]);
Console.WriteLine();
Console.WriteLine("=============");
Console.WriteLine("FOR EXAMPLE");
Console.WriteLine("=============");
Lysia.Program.RunFile(["Examples/for"]);
Console.WriteLine();
Console.WriteLine("=============");
Console.WriteLine("FUNC EXAMPLE");
Console.WriteLine("=============");
Lysia.Program.RunFile(["Examples/func"]);
Console.WriteLine();
Console.WriteLine("=============");
Console.WriteLine("FILE EXAMPLE");
Console.WriteLine("=============");
Lysia.Program.RunFile(["Examples/file"]);
Console.WriteLine();
Console.WriteLine("=============");
Console.WriteLine("EXTERN MODULE EXAMPLE");
Console.WriteLine("=============");
Lysia.Program.RunFile(["Examples/externModule"]);